services:
  - postgres

before_script:
  - bin/bundle install --jobs $(nproc) --path /cache

cache:
  key: "$CI_BUILD_REF_NAME"
  untracked: true

rspec:
  script:
    - bin/rspec

rubocop:
  script:
    - bin/rake rubocop
