variables:
  DATABASE_HOST: postgres
  POSTGRES_DB: gearscore_test
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ""
  RAILS_ENV: test

services:
  - postgres

before_script:
  - bin/bundle install --jobs $(nproc) --path /cache

cache:
  key: "$CI_BUILD_REF_NAME"
  untracked: true

rspec:
  script:
    - bin/rspec

lint:
  script:
    - bin/rake rubocop
    - bin/rake scss_lint
