require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

RSpec/ExampleLength:
  Max: 10

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/Documentation:
  Enabled: false

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/StringLiterals:
  Enabled: false
